DEFAULT_CHUNK_SIZE = 800
DEFAULT_CHUNK_OVERLAP = 100
DEFAULT_SEMANTIC_THRESHOLD = 0.5
DEFAULT_TOP_K = 3
DEFAULT_EMBEDDING_MODEL = "all-MiniLM-L6-v2"
DEFAULT_GENERATIVE_MODEL = "gemini-2.5-flash"
DEFAULT_COLLECTION_NAME = "markdown_docs"
